In [1]:
import numpy as np

In [2]:
# создадим массив numpy
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
# выведем нулевой элемент данного массива
a[0]

0

In [4]:
# заменим значение 1ого элемента массива
a[1] = 20
a

array([ 0, 20,  2,  3,  4,  5,  6,  7,  8])

In [5]:
# обратимся к последнему элементу массива
a[-1]

8

In [6]:
# посмотрим размерность массива a
a.shape

(9,)

In [7]:
# выведем максимальный элемент (последний) начиная с начала
a[8]

8

In [8]:
# при этом a[-8] это будет не начальный элемент, так как отчет с конца начинается с -1
a[-8]

20

In [9]:
# обратимся к нулевому элементу, начиная с конца
a[-9]

0

In [10]:
# при попытке вывести девятый элемент мы должны увидеть ошибку, так как вышли за границы массива
a[9]

IndexError: index 9 is out of bounds for axis 0 with size 9

In [ ]:
# аналогично при выход за пределы в отрицательную сторону мы увидем ошибку
a[-10]

Как мы поняли, работа с одномерными массивами в numpy такая же, как и с одномерными списками в python. А вот в работе с многомерными массивами numpy уже есть свои нюансы (отличия).


In [12]:
# создадим двумерный массив b
b = np.array([[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14]])
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
# так мы можем обратиться к элемену, что находится во 2 строке на 3ем месте
# но так как отсчет начинается с 0, то в numpy нам понадобится обратиться к 1 строке и 2ому элементу для этого
b[1, 2]

7

In [14]:
# выведем размерность массива b
b.shape

(3, 5)

In [15]:
# если при обращении к массиву мы указываем меньше индексов, чем размерность самого массива
# то вместо конкретного элемента последнего (недостоющего индекса) будет выведена вся строка, ниже пример
b[1]

array([5, 6, 7, 8, 9])

In [16]:
# также, если мы хотим обратиться к конкретному элементу двумерного массива, мы это можем сделать таким способом
b[1][2] # так работает индексация в многомерных списках python, она работает и здесь в numpy
b[1, 2] # но такой способ обращения к элементу предпочтительнее, так как действие выполняется единожды


7

In [17]:
# при помощи такой индексации мы можем и менять значение конкретного элемента
b[1, 2] = 70
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 70,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
# также можно обратиться к конкретному элементу через кортеж
i = (2, 3)
b[i] # аргумент индексации

13

Срезы numpy

In [19]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 70,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
b.shape

(3, 5)

In [21]:
# обратимся к строке с индексом 1
b[1, :]
b[1]
# это в данном случае идентичные записи

array([ 5,  6, 70,  8,  9])

In [22]:
# срез без определенных границ позволяет получать проекцию по любым осям
b[:, 1] # в данном случае вывели все строки столбца с индексом 1

array([ 1,  6, 11])

In [23]:
# сделаем срез двух первых строк и всех столбцов массива b
b[0:2, :] # поним о том, что при указании среза правая граница не включается
# тоесть на вывод идут строки с индексами 0, 1 (строка с индексом 2 погнаничная и не включается)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 70,  8,  9]])

In [24]:
# выведем нижнюю строчку начиная со второго столбца
b[2, 1:]

array([11, 12, 13, 14])

In [25]:
# выведем первые две строчки в 3 и 4 столбцах
b[:2, 2:4]

array([[ 2,  3],
       [70,  8]])

In [26]:
# веведем столбцы через один, начиная с первого; сделать это можно задав шаг 2
b[:, ::2]

array([[ 0,  2,  4],
       [ 5, 70,  9],
       [10, 12, 14]])

In [27]:
# срезы, взятые с какого-то массива также можно присвоить в другую переменную
b_s2 = b[::2, ::3]
b_s2

array([[ 0,  3],
       [10, 13]])

При получении среза массива создается объект-предстваление (array view), работая с данными исходного массива, определяя для него специальный порядок обхода элементов.

In [28]:
# опеределение, содержит ли объект данные или является представлением данных другого объекта
b.flags.owndata, b_s2.flags.owndata # b_s2 показал False, так как это срез с массива b

(True, False)

In [29]:
b_s2[0, 0]

0

In [30]:
b_s2[0, 0] = 10 # меняем левый верхний элемент среза на 10

In [32]:
b_s2[0, 0]

10

In [34]:
b # как мы можем убедиться в исходном массиве данный элемент также изменился

array([[10,  1,  2,  3,  4],
       [ 5,  6, 70,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
# чтобы значение исходного массива не нарушалось, можно исходный массив скопировать в другую переменную
# использую специальный инструмент
b2 = b.copy()
b2

array([[10,  1,  2,  3,  4],
       [ 5,  6, 70,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
b2[::2, ::3]

array([[10,  3],
       [10, 13]])

In [39]:
b2[::2, ::3] = [[-1, -2], [-4, -5]] # присвоенеие срезу многомерной структуры совпадающей размерности
b2

array([[-1,  1,  2, -2,  4],
       [ 5,  6, 70,  8,  9],
       [-4, 11, 12, -5, 14]])

In [41]:
b2[2, 1:]

array([11, 12, -5, 14])

In [43]:
b2[2, 1:] = 110 # присвоение среза скалярного значения за счет распространения
b2 # заметим, что значение 110 присвоилось всей группе элементов их среза

array([[ -1,   1,   2,  -2,   4],
       [  5,   6,  70,   8,   9],
       [ -4, 110, 110, 110, 110]])

Работа с функциями Numpy
А именно работа с универсальными функциями

In [44]:
b

array([[10,  1,  2,  3,  4],
       [ 5,  6, 70,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
b < 7 # произошла проверка и вывод логического значения для каждого элемента массива

array([[False,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False]])

In [48]:
(3 < b) & (b < 7) # аналогично проверка и совмещение конъюнкцией

array([[False, False, False, False,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False]])

In [50]:
b + 10 # операция происходит над каждым элементом массива

array([[20, 11, 12, 13, 14],
       [15, 16, 80, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
b * 10 # аналогично с умножением

array([[100,  10,  20,  30,  40],
       [ 50,  60, 700,  80,  90],
       [100, 110, 120, 130, 140]])

In [52]:
b + b # тут каждый элемент матрицы b складывается соответственно с каждым элементом матрицы b

array([[ 20,   2,   4,   6,   8],
       [ 10,  12, 140,  16,  18],
       [ 20,  22,  24,  26,  28]])

In [54]:
b * b # аналогично с умножением (это именно поэлементное умножение, это НЕ матричное умножение)

array([[ 100,    1,    4,    9,   16],
       [  25,   36, 4900,   64,   81],
       [ 100,  121,  144,  169,  196]])

In [56]:
np.exp(b) # возведение экспоненты в степень b (экспонента возводится в степень каждого элемента b)

array([[2.20264658e+04, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 2.51543867e+30, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

In [59]:
a0 = np.arange(5) # создадим массив от 0 до 4
a0

array([0, 1, 2, 3, 4])

In [63]:
b0 = np.arange(0, 50, 10) # создадим другой массив от 0 до 40 вкл с шагом 10
b0

array([ 0, 10, 20, 30, 40])

In [64]:
c0 = a0 + b0 # сложим эти два массива (каждый элемент одного массива сложится с соотв. элементом другого)
c0

array([ 0, 11, 22, 33, 44])

Оси и агрегирующие функции

In [66]:
# создадим массив 3х5
ar1 = np.arange(15).reshape(3, 5)
ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
ar1.shape

(3, 5)

In [69]:
ar1.sum() # суммируем элементы массива

105

In [71]:
ar1.sum(axis=None) # аналогично суммируем как и выше, заметим, что элемент axis по умолчанию None
# axis показывает вдоль какой оси мы будем суммировать

105

In [72]:
# чтобы просуммировать постолбцам первое значение axis должно стоять 0
ar1.sum(axis = 0)

array([15, 18, 21, 24, 27])

In [73]:
ar1.sum(axis = 0).shape # проверямем форму данного среза

(5,)

In [74]:
# чтобы проссумировать по строкам параметр axis должен принимать значение 1
ar1.sum(axis = 1)

array([10, 35, 60])

Линейная алгебра в Numpy

In [78]:
# создадим массив
e = np.array([[0, 1, 2, 3, 4],
             [10, 11, 12, 13, 14],
             [20, 21, 22, 23, 24],
             [30, 31, 32, 33, 34],
             [40, 41, 42, 43, 44]])

In [79]:
e * 10

array([[  0,  10,  20,  30,  40],
       [100, 110, 120, 130, 140],
       [200, 210, 220, 230, 240],
       [300, 310, 320, 330, 340],
       [400, 410, 420, 430, 440]])

In [80]:
e * e

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [81]:
e / 2 # можем поэлемнтно делить

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 5. ,  5.5,  6. ,  6.5,  7. ],
       [10. , 10.5, 11. , 11.5, 12. ],
       [15. , 15.5, 16. , 16.5, 17. ],
       [20. , 20.5, 21. , 21.5, 22. ]])

In [84]:
# создадим 2 марицы 3х3 и 3х2 размерностью
m1 = np.arange(9).reshape(3, 3)
m2 = np.arange(6).reshape(3, 2)
print(m1)
print(m2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]


In [87]:
# теперь перемножим использую матричное умножение
# (чтобы оно было возможно - кол-во столбцов первой матрицы, должно быть равно кол-ву строк второй матрицы)
m3 = np.dot(m1, m2)
m3

array([[10, 13],
       [28, 40],
       [46, 67]])

In [88]:
m1.shape, m2.shape, m3.shape

((3, 3), (3, 2), (3, 2))

In [89]:
m1 @ m2 # бинарный оператор, аналогичный dot()

array([[10, 13],
       [28, 40],
       [46, 67]])

In [90]:
m2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [91]:
m2.T # транспонированная матрица m2

array([[0, 2, 4],
       [1, 3, 5]])

In [92]:
m2_1 = m2[:, 1]
m2_1, m2_1.shape # выводит в форме одномерного массива, а не столбца ВНИМАТЕЛЬНО

(array([1, 3, 5]), (3,))

In [94]:
# попробуем полученный путем среза выше одномерный массив транспонировать и увидим, что вектор столбца не создается
m2_1.T

array([1, 3, 5])

In [95]:
# если же нам все-таки нужно транспанировать одномерный массив в виде столбца, то делаем следующее
m2_1l = m2_1[np.newaxis, :] # создаем "матрицу-строку", парметр newaxis создает новую ось
print(m2_1l, m2_1l.shape, '\n') # при выводе размерности мы видим, что это уже матрица с 1 строкой и 3 столбцами
print(m2_1l.T, m2_1l.T.shape) # в таком виде она легко транспонируется

[[1 3 5]] (1, 3) 

[[1]
 [3]
 [5]] (3, 1)


In [96]:
m2_1[:, np.newaxis] # делаем "матрицу-столбец" напрямую (минуя этап транспонирования)

array([[1],
       [3],
       [5]])

In [97]:
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
m2.T

array([[0, 2, 4],
       [1, 3, 5]])

In [99]:
m2.T @ m1

array([[30, 36, 42],
       [39, 48, 57]])

In [101]:
# можем также найти определитель матрицы m1
np.linalg.det(m1)

0.0

In [103]:
m3 = np.array([[3, 7, 4], [11, 2, 9], [4, 11, 2]])
m3

array([[ 3,  7,  4],
       [11,  2,  9],
       [ 4, 11,  2]])

In [105]:
np.linalg.det(m3) # тут из-за округлений мы увидим не совсем точное число, если вычислять вручную, это будет 265 ровно


265.00000000000017

In [106]:
m3i = np.linalg.inv(m3) # получение обратной матрицы с помощью метода inv
m3i

array([[-0.35849057,  0.11320755,  0.20754717],
       [ 0.05283019, -0.03773585,  0.06415094],
       [ 0.42641509, -0.01886792, -0.26792453]])

In [108]:
# по идее если матрицу перемножить на обратную ей матрицу, то должна получиться единичная матрица
# единичная - это такая, на главноей диагонали которой единицы, а остальные числа нули
m3 @ m3i # на выводе мы видим, что на главной действительно едеиницы, но остальные числа не нули (виновато округление)

array([[ 1.00000000e+00,  5.55111512e-17,  0.00000000e+00],
       [ 1.66533454e-16,  1.00000000e+00, -2.22044605e-16],
       [ 1.11022302e-16, -2.08166817e-17,  1.00000000e+00]])